POST localhost:3001/api/blogs
Content-Type: application/json

{
  "title": "Example Blog 2",
  "author": "Surya V",
  "url": "www.example.com",
  "likes": 342323,
  "user": "66b4add6363999520e6b38ac"
}

###
GET localhost:3001/api/blogs