DELETE localhost:3001/api/blogs/66b4ed5627255c3183a968c2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InN1cnlhX3YiLCJpZCI6IjY2YjRlYzE4NWRlNzQwN2IzNmQ0MmQ5MyIsImlhdCI6MTcyMzEzMzE5MywiZXhwIjoxNzIzMTM2NzkzfQ.7VLybtiEjbDInrZ5aeEKsY_RE9lwRONjP-DhLRsE2tg