DELETE localhost:3001/api/blogs/66b4bd2d2292e45d01bf044a
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFyaXN0b3RsZSAiLCJpZCI6IjY2YjRkOWMyMjg0NmI1ZGQyNjZlZDcxNiIsImlhdCI6MTcyMzEyODI2NywiZXhwIjoxNzIzMTMxODY3fQ.hEdGi0MzJ74cJqTfXn36ccYWA9PuTvSeXgoon0BMGCY